excluded:
  - Carthage
  - example-objc
  - example-swift
  - vendor/bundle/ruby/
  - .build
disabled_rules:
  - xctfail_message
  - identifier_name
  - large_tuple
# custom
function_parameter_count: 6
file_length: 500
