version: 2

machine:
  - &defaults
    macos:
      xcode: "12.0.1"
    shell: /bin/bash --login -eo pipefail
    working_directory: /Users/distiller/project

cache_step:
  - gem_cache:
      primary: &primary_cache_key_gem gem-v2-{{ checksum "Gemfile.lock" }}
      keys: &all_cache_keys_gem
        - *primary_cache_key_gem
        - gem-v2-
  - carthage_cache:
      primary: &primary_cache_key_carthage carthage-v1-{{ checksum "Cartfile.resolved" }}
      keys: &all_cache_keys_carthage
        - *primary_cache_key_carthage
        - carthage-v1-
  - restore_cache: &restore_cache_carthage
      keys: *all_cache_keys_carthage
  - save_cache: &save_cache_carthage
      paths:
        - Carthage
      key: *primary_cache_key_carthage
  - restore_cache: &restore_cache_gem
      keys: *all_cache_keys_gem
  - save_cache: &save_cache_gem
      paths:
        - vendor/bundle
      key: *primary_cache_key_gem

shared_build_step:
  - run: &set_env
      command: |
        echo "export REPOSITORY_ROOT=$(git rev-parse --show-toplevel)" >> $BASH_ENV
        echo "source $CIRCLE_WORKING_DIRECTORY/scripts/bash.source" >> $BASH_ENV
        source $BASH_ENV

  - run: &bundle_install
      name: bundle install
      command: |
        bundle config set deployment 'true'
        bundle config set clean 'true'
        bundle install --jobs 4 --retry 3

  - run: &brew_install
      name: install via HomeBrew
      command: |
        brew bundle
        cat Brewfile.lock.json

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: *set_env
      - restore_cache: *restore_cache_gem
      - run: *bundle_install
      - save_cache: *save_cache_gem
      - run: *brew_install
      - run: bundle exec danger
      - run: bundle exec fastlane ios check_swift_format
      - run: bundle exec fastlane ios check_objc_format
      - run: bundle exec fastlane ios lint_podspec
      - restore_cache: *restore_cache_carthage
      - run: bundle exec fastlane ios carthage_bootstrap
      - save_cache: *save_cache_carthage
      - run: bundle exec fastlane ios test
      - run: bundle exec fastlane ios build_swiftpm

  create_pr_to_public:
    <<: *defaults
    steps:
      - checkout
      - run: *set_env
      - restore_cache: *restore_cache_gem
      - run: *bundle_install
      - run: bundle exec fastlane ios create_pr_to_public

  create_pr_to_update_docs:
    <<: *defaults
    steps:
      - checkout
      - run: *set_env
      - restore_cache: *restore_cache_gem
      - run: *bundle_install
      - run: bundle exec fastlane ios create_pr_to_update_docs

  distribute_sample_app:
    <<: *defaults
    steps:
      - checkout
      - run: *set_env
      - run: curl -sL firebase.tools | bash
      - restore_cache: *restore_cache_gem
      - run: *bundle_install
      - run: bundle exec pod install --repo-update --project-directory=example-objc
      - run: bundle exec fastlane ios distribute_sample_app

  build_example:
    <<: *defaults
    steps:
      - checkout
      - run: *set_env
      - restore_cache: *restore_cache_gem
      - run: *bundle_install
      - run: *brew_install
      - run: bundle exec fastlane ios build_carthage_swift_example
      - run: bundle exec fastlane ios build_cocoapods_objc_example

workflows:
  version: 2
  default_flow:
    jobs:
      - build
      - create_pr_to_public:
          requires:
            - build
          filters:
              branches:
                only: master
      - create_pr_to_update_docs:
          requires:
            - build
          filters:
              branches:
                only: develop
      - distribute_sample_app:
          requires:
            - build
          filters:
              branches:
                only: develop
      - build_example:
          requires:
            - build
          filters:
              branches:
                only: develop