name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

env:
  CACHE_NUMBER: 0

jobs:
  build:
    runs-on: macos-10.15
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Install HomeBrew
        run: |
          brew bundle || true
          cat Brewfile.lock.json || true
      - name: Select Xcode
        run: sudo xcode-select -s '/Applications/Xcode_12.2.app/Contents/Developer'
      - run: xcodebuild -version
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ env.CACHE_NUMBER }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-${{ env.CACHE_NUMBER }}-
      - name: Install gems
        run: |
          bundle config set deployment 'true'
          bundle config set clean 'true'
          bundle install --jobs 4 --retry 3
      - uses: actions/cache@v2
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ env.CACHE_NUMBER }}-${{ hashFiles('Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-carthage-${{ env.CACHE_NUMBER }}-
      - run: bundle exec fastlane ios carthage_bootstrap
      - run: bundle exec fastlane ios check_swift_format
      - run: bundle exec fastlane ios check_objc_format
      - run: bundle exec fastlane ios test
      - run: bundle exec fastlane ios lint_podspec
      - run: bundle exec fastlane ios build_swiftpm
      - run: bundle exec fastlane ios build_carthage_swift_example
      - run: bundle exec fastlane ios build_cocoapods_objc_example




