name: release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: macos-14
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install Gems
        run: |
          bundle config set deployment 'true'
          bundle config set clean 'true'
          bundle install --jobs 4 --retry 3
      - name: lint podspec
        run: bundle exec fastlane ios lint_podspec
      - name: publish to pod trunk
        run: |
          bundle exec pod trunk push PAYJP.podspec
          bundle exec pod trunk push PAYJPFlutterCore.podspec
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
