name: Update Docs

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Install HomeBrew
        run: |
          brew bundle || true
          cat Brewfile.lock.json || true
      - run: xcodebuild -version
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install gems
        run: |
          bundle config set deployment 'true'
          bundle config set clean 'true'
          bundle install --jobs 4 --retry 3
      - run: bundle exec fastlane ios create_pr_to_update_docs
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
